src/app/shared/inline-edit.component.html, src/app/shared/orcid-input-box.component.html, src/app/shared/orcid-input-box.component.ts, src/app/submission-shared/date-input.component.ts, src/app/submission-shared/pubmedid-search/pubmedid-search.component.css, src/app/submission-shared/pubmedid-search/pubmedid-search.component.html, src/app/submission-shared/pubmedid-search/pubmedid-search.component.ts, src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-grid.component.ts, src/app/submission/edit/subm-form/feature/subm-feature.component.ts, src/app/submission/edit/subm-form/field/subm-field.component.html, src/app/submission/edit/subm-form/field/subm-field.component.ts, src/app/submission/edit/subm-sidebar/subm-sidebar.component.html, src/app/submission/shared/default.template.ts, src/app/submission/shared/submission-type.model.ts, src/app/submission/shared/submission.model.ts, src/styles/custom-variables.less, src/styles/misc.less
PubMed ID lookup field implemented in the vein of an auto-suggest search box where the suggestion acts as a preview of the with confirmation from the user by selection. It fetches publication data on de-bounced key presses, supports the enter key and allows for any previously fetched publication data to be displayed again (1st enter key press) or actioned upon (2nd key press).
The submission field component is updated to support an "async" event for data fetched asynchronously. The event is used in features to automatically set all inputs belonging to a given row (the one where the search box is present).
=> Pubmed ID search box

src/app/auth/user-data.ts, src/app/auth/user-role.ts, src/app/submission/direct-submit/direct-submit.component.html, src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-grid.component.ts
Right now the tool lacks any authorisation logic and instead hard-codes the current user's role to `User.Public`. 
Until the tool is refactored to support different user roles, all edition capabilities are restricted to non-public users, effectively disabling them for now. This is in line with the production version as of 15/1/2018.
=> Locked mode for grids only

src/app/shared/confirm-dialog.component.html, src/app/shared/confirm-dialog.component.ts, src/app/submission/edit/subm-edit.component.ts
Fixes the limbo state the app is left in when dismissing a confirmation modal on backdrop click.
=> Fixes backdrop click limbo.

src/app/shared/inline-edit.component.css, src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.css, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-grid.component.ts, src/app/submission/edit/subm-form/feature/feature-list.component.html, src/app/submission/edit/subm-form/feature/feature-list.component.ts, src/app/submission/edit/subm-form/feature/subm-feature.component.html, src/app/submission/edit/subm-form/feature/subm-feature.component.ts, src/app/submission/edit/subm-form/subm-form.component.ts, src/app/submission/edit/subm-form/subm-form.service.ts, src/app/submission/edit/subm-sidebar/subm-sidebar.component.html, src/app/submission/edit/subm-sidebar/subm-sidebar.component.ts, src/app/submission/shared/default.template.ts, src/app/submission/shared/submission-type.model.ts, src/app/submission/shared/submission.model.ts, src/app/submission/shared/unique.directive.ts, src/styles/custom-layout.less
Adds a typeahead to both column and data fields in the submission edit view. Additionally, it checks for uniqueness of column values, showing a validation popover on focus –in line with validation everywhere else– and blocking submission if applicable.
=> Autocomplete for submission fields

src/app/auth/user-data.ts, src/app/submission-shared/date-input.component.html, src/app/submission-shared/date-input.component.ts, src/app/submission/direct-submit/direct-submit-sidebar.component.html, src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-grid.component.ts, src/app/submission/edit/subm-form/feature/feature-list.component.html, src/app/submission/edit/subm-form/feature/subm-feature.component.html, src/app/submission/edit/subm-form/feature/subm-feature.component.ts, src/app/submission/edit/subm-form/field/subm-field.component.html, src/app/submission/edit/subm-form/field/subm-field.component.ts, src/app/submission/edit/subm-form/subm-form.component.html, src/app/submission/edit/subm-navbar/subm-validation-errors.component.html, src/app/submission/edit/subm-sidebar/subm-sidebar.component.ts, src/app/submission/list/ag-grid/date-filter.component.html, src/app/submission/list/ag-grid/date-filter.component.ts, src/app/submission/list/ag-grid/text-filter.component.html, src/app/submission/list/ag-grid/text-filter.component.ts, src/app/submission/list/subm-list.component.ts, src/app/submission/shared/default.template.ts, src/app/submission/shared/hecatos.template.ts, src/app/submission/shared/pagetab-attributes.utils.ts, src/app/submission/shared/submission-type.model.ts, src/app/submission/shared/submission.model.ts, src/app/submission/shared/unique.directive.ts, src/styles/custom-layout.less, src/styles/misc.less
- Takes advantage of PageTab's specs to allow duplicates, paving the way for compatibility with HeCaToS (factor name annotations). Numerical suffixing of column names together with column uniqueness validation are both optional now. 
- Improves UX for column filters on submission list:
- Adds a clear button.
- Closes popup on button press.
- Uses a sieve icon to convey both the state of filtering and the presence of filtering options.
- Makes date filter's UI clearer: turns out "From" and "To" dates behave differently.
- Fixes disabled state for date picker's back button and prevents the click event from bubbling up to the body element (was problematic in combination with ag-Grid's popups).
- Guarantees fitting of popovers within feature widgets by making their styling responsive.
- …
=> HeCaToS, column filters and other improvements

src/app/submission/edit/subm-add/subm-add.component.html, src/app/submission/edit/subm-add/subm-add.component.ts, src/app/submission/edit/subm-edit.component.html, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-list.component.html, src/app/submission/edit/subm-sidebar/subm-sidebar.component.html, src/app/submission/edit/subm-sidebar/subm-sidebar.component.ts, src/app/submission/shared/default.template.ts, src/app/submission/shared/submission-type.model.ts, src/app/submission/shared/unique.directive.ts
- Allows uniqueness to be overridden by property even for annotations. 
- Applies the uniqueness test if no value for the directive is passed in.
- Refactors new type dialogue so that validation takes place before actually adding the type.
- Uses dashed cues for optional feature fields only on the submission edit view.
=> Uniqueness test fixes.

src/app/app.config.ts
When the user goes directly to a submission view via URL, an exception occurs due to a malformed URL. The text description for the exception goes along the following lines:
`ServerError: [404] [HTTP/2.0 404] Http failure response for https://localhost:4200/undefined/api/submissions/S-BSST18`
The problem is exacerbated on Safari. It has to do with the way an observable within the logic for the `APP_INITIALIZER` injector token [was being handled](https://stackoverflow.com/a/40222544).
=> Fix for direct navigation exception

src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-list.component.html, src/app/submission/edit/subm-form/feature/subm-feature.component.ts, src/app/submission/edit/subm-form/subm-form.component.html, src/app/submission/shared/default.template.ts, src/app/submission/shared/hecatos.template.ts, src/app/submission/shared/submission-type.model.ts, src/app/submission/shared/submission.model.ts
Some attributes and its values need to be readonly, even when showing the edit view. For that purpose, the "readonly" property is introduced in type templates. It makes both columns and fields (be them top-level ones of member of a column's field group) be un-editable.
=> Readonly fields and columns

src/app/shared/inline-edit.component.html, src/app/shared/inline-edit.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-grid.component.ts, src/app/submission/edit/subm-form/feature/feature-list.component.html, src/app/submission/edit/subm-form/feature/feature-list.component.ts, src/app/submission/list/subm-add.component.html, src/app/submission/list/subm-list.component.ts, src/app/submission/shared/default.template.ts, src/app/submission/shared/hecatos.template.ts, src/app/submission/shared/submission-type.model.ts, src/app/submission/shared/submission.model.ts
Adds a "removable" column property to type templates. It caters for cases whereby the column may not be required or, while its name can be changed, the column itself may not be removed. For example, the PubMed ID column: it's not required but it should be displayed and may not be removed.
=> Removable columns

src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-list.component.html, src/app/submission/edit/subm-form/feature/subm-feature.component.html, src/app/submission/shared/pagetab.model.ts, src/app/submission/shared/submission.model.ts
When showing the results of a submission, optional features with whole rows empty are rendered without filtering out said rows. Now, every time a whole feature or a row is rendered on read-only mode (the one employed in the submission results view), it is tested for emptiness at the ValueMap level.
=> Prevents the rendering of empty rows or wholly empty features

src/app/auth/user-data.ts, src/app/submission-shared/date.utils.ts, src/app/submission/direct-submit/direct-submit-sidebar.component.ts, src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-navbar/subm-navbar.component.html, src/app/submission/edit/subm-navbar/subm-navbar.component.ts, src/app/submission/list/subm-add.component.ts, src/app/submission/list/subm-list.component.html, src/app/submission/list/subm-list.component.ts, src/app/submission/shared/submission-type.model.ts
Different users will have been granted different rights regarding which projects they can attach submissions to. Therefore, the list of templates available to the user should inevitably be limited to the projects the user in question has been given rights for. This is what this update does, treating the list of projects as part of the logged-in user's data. This opens up the possibility caching the said list, avoiding multiple requests for, basically, the same information within a session.
=> ACL-filtered template selection

src/app/app.config.ts, src/app/auth/user-data.spec.ts, src/app/file/file-list.component.ts, src/app/file/file.service.ts, src/app/help/help.component.css, src/app/help/help.component.html, src/app/submission-shared/date-input.component.ts, src/app/submission-shared/pubmedid-search/pubmedid-search.component.css, src/app/submission/direct-submit/direct-submit-sidebar.component.css, src/app/submission/direct-submit/direct-submit-sidebar.component.html, src/app/submission/direct-submit/direct-submit-sidebar.component.ts, src/app/submission/direct-submit/direct-submit.component.html, src/app/submission/direct-submit/direct-submit.component.ts, src/app/submission/direct-submit/direct-submit.service.ts, src/app/submission/edit/subm-edit.component.html, src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-form/field/subm-field.component.html, src/app/submission/edit/subm-form/field/subm-field.component.ts, src/app/submission/edit/subm-form/subm-form.service.ts, src/app/submission/list/subm-add.component.html, src/app/submission/list/subm-add.component.ts, src/app/submission/list/subm-list.component.html, src/app/submission/list/subm-list.component.ts, src/app/submission/results/results-log-node.component.ts, src/app/submission/results/subm-results-modal.component.html, src/app/submission/results/subm-results-modal.component.ts, src/app/submission/shared/default.template.ts, src/app/submission/shared/hecatos.template.ts, src/styles/custom-layout.less, src/styles/misc.less
- File list view fixes:
- Fixes exception when switching from files view to submissions list before request completion.
- Encodes file paths before deletion request to fix `File not found` server error.
- Submission form improvements (manual & direct submit)
- Switches to check tab automatically on pressing the submit button if errors present.
- Fixes wrong pending fields counter when required fields within optional features are highlighted.
- Sets datepicker's maximum date to 2 years ahead for release date field.
- Bring highlighting style for PubMed search drop-up in line with rest of the app.
- Unpacks the "Submit as" button in the direct submit's sidebar into clear radio buttons with "Create" as a default.
- Submission results improvements (manual & direct submit)
- Makes "Please …
=> Submission form and state improvements + UI fixes

src/app/submission/edit/subm-edit.component.ts
Views in Angular are detached before being destroyed. In the interim, if there is any change event, this can bubble up while the view is detached. This is the case when the user changes a field and, without blurring it, decides to navigate away from the view. The present commit addresses this edge case.
=> Prevents save after destruction

src/app/file/file-list.component.ts, src/app/submission/edit/subm-edit.component.html, src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-sidebar/subm-sidebar.component.html, src/app/submission/edit/subm-sidebar/subm-sidebar.component.ts, src/app/submission/list/subm-list.component.ts, src/styles/custom-layout.less
- Normalises error messages coming from the server when retrieving a certain submission and shows them on the side-bar. This means that alerts won't be used in this case.
- Hides the navbar and the "Add" tab to reflect the absence of a submission if retrieval fails.
- Makes the cog animation for Ag-Grid's loading state slightly bigger.
=> Error state for subm edit and other improvements

src/app/core/header/global-error.component.html, src/app/core/header/global-error.component.ts, src/app/file/file-list.component.ts, src/app/file/file-upload-badge.component.html, src/app/file/file-upload-badge.component.ts, src/app/file/file-upload.service.ts, src/app/http/http-custom-client.service.ts, src/app/submission/list/subm-list.component.ts
- Changes the colour of the upload button's badge to red when an error occurs while uploading.
- Improves the styling and text for the "Progress" column in the event of failure.
- Widens the range of error objects accepted by the GlobalErrorHandler class to include plain strings. This paves the way for more meaningful errors from request failures.
- Detects if the there is no network at the global level, printing out a "please check"-type of error if not.
- Improves documentation and naming conventions.
=> Graceful recovery from file upload errors

src/app/auth/signup/signup.component.html, src/app/auth/signup/signup.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.css, src/styles/custom-layout.less, src/styles/custom-navbar.less, src/styles/custom-variables.less
- Implements a clickwrap on the signup view in line with GDPR requirements .
- Fixes minor cross-browser issues with Firefox versions previous to v48:
- Z-indexing is broken due to [calc's lack of support for unit-less numbers](https://bugzilla.mozilla.org/show_bug.cgi?id=594933). LESS constants are used instead.
- Canton cell in grids appears dislodged. Left floating is preserved for them.
=> Clickwrap and UI fixes

config.json, src/app/app.config.ts, src/app/shared/inline-edit.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-list.component.html, src/app/submission/edit/subm-form/field/subm-field.component.html, src/app/submission/edit/subm-form/field/subm-field.component.ts, src/app/submission/edit/subm-form/subm-form.component.html, src/config.json
Exposes two internal parameters as global constants: typeahead's suggestion length and datepicker's max number of years into the future.
=> Minor changes to app's config surface.

src/app/auth-guard.service.ts, src/app/core/header/global-error.component.ts, src/app/file/file-list.component.ts, src/app/file/file.service.ts, src/app/shared/inline-edit.component.html, src/app/shared/inline-edit.component.ts, src/app/submission-shared/date-input.component.ts, src/app/submission-shared/file-input.component.ts, src/app/submission/direct-submit/direct-submit-sidebar.component.ts, src/app/submission/edit/subm-edit.component.ts, src/app/submission/edit/subm-form/feature/feature-grid.component.html, src/app/submission/edit/subm-form/feature/feature-grid.component.ts, src/app/submission/edit/subm-form/feature/feature-list.component.html, src/app/submission/edit/subm-form/feature/feature-list.component.ts, src/app/submission/edit/subm-form/field/subm-field.component.ts, src/app/submission/edit/subm-form/subm-form.component.html, src/app/submission/edit/subm-form/subm-form.component.ts, src/app/submission/edit/subm-form/subm-form.service.ts, src/app/submission/shared/submission.model.ts, src/app/submission/shared/unique.directive.ts
- Due to the [deprecation of edge-case mixed templates in Angular 7](https://next.angular.io/api/forms/FormControlName#use-with-ngmodel), it removes the ngModel directive wherever necessary, using the DOM change event to propagate new values to the submission model. This is a temporary solution until the disconnection between said model and the form controls –an architectural decision embedded into the codebase [very early on](https://github.com/EBIBioStudies/BioStudyUISub/commit/57ceb5463d5220e13a72b2cb43109e6e597b7743#diff-9f647c6cf0f4180c235ead5f7b38677cL23)– is removed. 
- Caches the first response for user files to avoid further requests every time a file input control is rendered within a file grid. This must be regarded as a temporary solution. In the longer term, the single …
=> NG 7 compliance and cached file list on submission edit

src/app/submission/submission-shared/model/templates/eutoxrisk.template.ts
After speaking with Ugis, he agreed to make the file description field optional in EU-ToxRisk template
=> File description in EU-ToxRisk template should be optional

src/app/file/file-list/file-list.component.ts, src/app/file/shared/file-upload-list.service.ts, src/app/file/shared/file.service.ts, src/app/file/shared/path.ts, src/app/submission/submission-direct/direct-submit-file-upload.service.ts, src/app/submission/submission-direct/direct-submit-sidebar.component.ts, src/app/submission/submission-direct/direct-submit.service.ts, src/app/submission/submission-direct/submission-direct.module.ts, src/app/submission/submission-list/subm-list.component.ts
When a user is direct uploading a submission, the system should upload the file before loading the submission. This will reduce the work a user has to do when submitting a file (excel) that contains metadata and data at the same time.
=> [165939281] Self-referencing direct upload issues

src/app/submission/submission-shared/model/pagetab-to-submission.utils.ts, src/app/submission/submission-shared/model/pagetab/pagetab-authors.utils.spec.ts, src/app/submission/submission-shared/model/pagetab/pagetab-authors.utils.ts, src/app/submission/submission-shared/model/pagetab/pagetab.model.ts, src/app/submission/submission-shared/model/submission-to-pagetab.utils.ts, src/app/submission/submission-shared/model/submission/submission.model.ts
In some cases, the user upload an study with a custom name for Org affiliation, like this:
```
Name	         Julianna Kobolák
E-mail	         julianna.kobolak@biotalentum.hu
Role	     PI
<affiliation>	BIOT
```
```
Organization    BIOT
Name    BioTalentum Ltd
```
We were replacing the `BIOT` value in the example with an `o1`, `o2`, etc.
With this fix it keeps the same affiliation relation.
=> Keep Org affiliation if the user provides a custom one through direct upload

src/app/pages/submission/submission-shared/model/templates/submission.templates.ts
`BioImages` is now a public template in `dev` and `beta` so it doesn't need to be in the public templates in the submission too.
=> Remove `BioImages` from public templates

src/app/pages/submission/submission-edit/subm-sidebar/subm-sidebar.component.ts, src/app/pages/submission/submission-shared/submission-to-pagetab.service.ts, src/app/shared/server-error.handler.ts
- Ensure keywords aren't extracted as attributes if they're empty
- Don't get error log if error is undefined
- Don't throw errors from sidebar as they're caught from submission edit service
=> Ensure keywords aren't extracted as attributes if they're empty

src/app/pages/submission/submission-edit/shared/form-validators.ts, src/app/pages/submission/submission-edit/shared/model/field-control.model.ts, src/app/pages/submission/submission-edit/subm-form/field/subm-field.component.ts, src/app/pages/submission/submission-shared/model/submission/submission.model.ts, src/app/pages/submission/submission-shared/model/submission/submission.validator.ts, src/app/pages/submission/submission-shared/submission-to-pagetab.service.ts, src/app/shared/dna-input/dna-input.component.ts, src/app/shared/protein-input/protein-input.component.ts
`ControlValueAccessor` doesn't support complex values for `onChange` function, it expects a `string` to trigger built in validations such as `Validations.required`. For DNA and Protein it was sending an object losing such built in validations.
=> Fix an issue validating DNA and Protein fields

src/app/pages/submission/submission-direct/direct-submit-file.component.html, src/app/pages/submission/submission-direct/direct-submit-file.component.ts, src/app/pages/submission/submission-direct/direct-submit-sidebar.component.html, src/app/pages/submission/submission-direct/direct-submit-sidebar.component.ts, src/app/pages/submission/submission-direct/direct-submit.component.html, src/app/pages/submission/submission-direct/direct-submit.service.ts
- Remove the submit types from the direct upload page.
- The backend already detects whether the study is new or already exists by querying the accNo in the direct upload file.
=> Remove upload action types from direct upload page

src/app/submission/submission-edit/shared/control-reference.ts, src/app/submission/submission-edit/subm-form/field/subm-field.component.ts, src/app/submission/submission-edit/subm-sidebar/subm-check-sidebar/subm-check-sidebar.component.html, src/app/submission/submission-edit/subm-sidebar/subm-edit-sidebar/subm-edit-sidebar.component.ts, src/app/submission/submission-shared/model/submission/submission.model.ts, src/app/submission/submission-shared/model/templates/arrayexpress.template.ts, src/app/submission/submission-shared/model/templates/bia.template.ts, src/app/submission/submission-shared/model/templates/default.template.ts, src/app/submission/submission-shared/model/templates/eutoxrisk.template.ts, src/app/submission/submission-shared/model/templates/hecatos.template.ts, src/app/submission/submission-shared/model/templates/proteindesigns.template.ts, src/app/submission/submission-shared/model/templates/submission-type.model.ts
Before it was using the `name` as title so if the name was composed of two or more words it was shown together. Release date is an example, it was displayed as `ReleaseDate` and with this change it should be displayed as `Release Date`.
=> Add support for field title

src/app/submission/submission-edit/shared/form-validators.ts
The standard validators in Angular don't trim the value so empty spaces were considered as part of the value. This PR adds custom validators so values are trimmed before to be validated.
=> Title validator ignores space
