- public/js/app.js
- public/js/submission/submission.service.js
- public/js/submission/views/editSubmission.ctrl.js
- public/js/submission/views/submission.html
- public/templates/bsng/section/bsContact.html
submit submission fix;
minor fixes on submission edit page...
> files page fix;

- package.json
- src/app/submission-shared/date-input.component.ts
- src/app/submission-shared/date.utils.ts
- src/app/submission/direct-submit/direct-submit.component.html
- src/app/submission/direct-submit/direct-submit.component.ts
- src/app/submission/edit/subm-edit.component.html
- src/app/submission/edit/subm-edit.component.ts
- src/app/submission/edit/subm-form/feature/feature-grid.component.ts
- src/app/submission/edit/subm-form/feature/feature-value.component.ts
- src/app/submission/edit/subm-form/field/subm-field.component.ts
- src/app/submission/edit/subm-form/subm-form.component.html
- src/app/submission/edit/subm-navbar/subm-navbar.component.html
- src/app/submission/edit/subm-navbar/subm-navbar.component.ts
- src/app/submission/edit/subm-navbar/subm-validation-errors.component.html
- src/app/submission/edit/subm-navbar/subm-validation-errors.component.ts
- src/app/submission/list/subm-list.component.ts
- src/app/submission/results/results-log-node.component.html
- src/app/submission/results/results-log-node.component.ts
- src/app/submission/results/subm-results-modal.component.html
- src/app/submission/results/subm-results-modal.component.ts
- src/app/submission/results/subm-results-tree.component.html
- src/app/submission/results/subm-results-tree.component.ts
- src/app/submission/shared/pagetab.model.spec.ts
- src/app/submission/shared/pagetab.model.ts
- src/app/submission/shared/submission.model.ts
- src/app/submission/shared/submission.service.ts
- src/app/submission/shared/submission.validator.spec.ts
- src/app/submission/shared/submission.validator.ts
- src/app/submission/submission.module.ts
* Added submission validation rules;
* Added dialog to show validation errors;
* Applied validation on submission changes (subm-edit.component)
* Updated onSubmit handler
* Fixed #80 issue with showing full tree log in submit results
> Submission validator

- src/app/submission/shared/default.template.ts
- src/app/submission/shared/submission-type.model.ts
- src/app/submission/shared/submission.model.feature.spec.ts
- src/app/submission/shared/submission.model.section.spec.ts
- src/app/submission/shared/submission.model.ts
- src/app/submission/shared/submission.validator.spec.ts
- src/app/submission/shared/txr.template.ts
introduces type scopes... so you can create two types of the same name in the same scope
> types model fix

- src/app/shared/confirm-dialog.component.html
- src/app/shared/confirm-dialog.component.ts
- src/app/submission-shared/tree-view.component.ts
- src/app/submission/direct-submit/direct-submit-sidebar.component.css
- src/app/submission/direct-submit/direct-submit-sidebar.component.html
- src/app/submission/direct-submit/direct-submit-sidebar.component.ts
- src/app/submission/edit/subm-add/subm-add.component.html
- src/app/submission/edit/subm-edit.component.css
- src/app/submission/edit/subm-edit.component.html
- src/app/submission/edit/subm-edit.component.ts
- src/app/submission/edit/subm-form/feature/feature-list.component.html
- src/app/submission/edit/subm-sidebar/subm-sidebar.component.html
- src/app/submission/list/subm-list.component.html
- src/app/submission/results/subm-results-modal.component.html
- src/app/submission/results/subm-results-modal.component.ts
- src/app/submission/shared/default.template.ts
- src/app/submission/shared/submission-type.model.ts
- src/app/submission/shared/submission.model.ts
- src/styles/custom-modal.less
- src/styles/custom-navbar.less
- src/styles/custom-normalize.less
- src/styles/custom-variables.less
Also fixes error when removing annotation column-like rows by giving annotations its own subclass of Feature.
> Splits confirmation modal into success and error modes + UX fixes

- src/app/auth/signin/signin.component.html
- src/app/auth/signup/signup.component.html
- src/app/core/header/header.component.html
- src/app/shared/inline-edit.component.css
- src/app/shared/inline-edit.component.html
- src/app/shared/inline-edit.component.ts
- src/app/submission-shared/date-input.component.ts
- src/app/submission/edit/subm-add/subm-add.component.html
- src/app/submission/edit/subm-edit.component.html
- src/app/submission/edit/subm-form/feature/feature-grid.component.css
- src/app/submission/edit/subm-form/feature/feature-grid.component.html
- src/app/submission/edit/subm-form/feature/feature-grid.component.ts
- src/app/submission/edit/subm-form/feature/feature-list.component.css
- src/app/submission/edit/subm-form/feature/feature-list.component.html
- src/app/submission/edit/subm-form/feature/feature-list.component.ts
- src/app/submission/edit/subm-form/feature/subm-feature.component.html
- src/app/submission/edit/subm-form/feature/subm-feature.component.ts
- src/app/submission/edit/subm-form/field/subm-field.component.html
- src/app/submission/edit/subm-form/subm-form.component.html
- src/app/submission/edit/subm-form/subm-form.service.ts
- src/app/submission/edit/subm-navbar/subm-navbar.component.html
- src/app/submission/edit/subm-navbar/subm-validation-errors.component.html
- src/app/submission/edit/subm-sidebar/subm-sidebar.component.html
- src/app/submission/list/subm-list.component.html
- src/app/submission/list/subm-list.component.ts
- src/app/submission/shared/default.template.ts
- src/styles/custom-layout.less
Turns out the update event was being ignored because its name was not being correctly retrieved. Apart from that, lots of small fixes, most UX-related.
> Fix multi-row validation error

- .angular-cli.json
- src/app/app.module.ts
- src/app/auth/signin/signin.component.html
- src/app/auth/signin/signin.component.ts
- src/app/auth/signup/signup.component.html
- src/app/core/header/header.component.html
- src/app/shared/inline-edit.component.css
- src/app/shared/orcid-input-box.component.ts
- src/app/submission-shared/date-input.component.css
- src/app/submission-shared/date-input.component.html
- src/app/submission-shared/date-input.component.ts
- src/app/submission-shared/date.utils.ts
- src/app/submission-shared/submission-shared.module.ts
- src/app/submission/direct-submit/direct-submit.component.html
- src/app/submission/edit/subm-edit.component.html
- src/app/submission/edit/subm-edit.component.ts
- src/app/submission/edit/subm-form/feature/feature-grid.component.css
- src/app/submission/edit/subm-form/feature/feature-grid.component.html
- src/app/submission/edit/subm-form/feature/feature-grid.component.ts
- src/app/submission/edit/subm-form/field/subm-field.component.html
- src/app/submission/edit/subm-form/subm-form.component.ts
- src/app/submission/edit/subm-navbar/subm-navbar.component.html
- src/app/submission/edit/subm-sidebar/subm-sidebar.component.css
- src/app/submission/edit/subm-sidebar/subm-sidebar.component.html
- src/app/submission/edit/subm-sidebar/subm-sidebar.component.ts
- src/app/submission/shared/default.template.ts
- src/styles/custom-layout.less
- src/styles/misc.less
Makes the interaction model with the date input more straight-forward by making the most of what is already provided by the ngx-bootstrap package and fixes change detection when picking a date.
> Refactors the date-input control class to fix UX issues

- src/app/file/file-list.component.html
- src/app/file/user-dirs-sidebar.component.ts
- src/app/shared/file-upload-button.component.ts
- src/app/shared/multi-select.component.ts
- src/app/shared/validate-onblur.directive.ts
- src/app/submission-shared/file-input.component.html
- src/app/submission-shared/tree-view.component.ts
- src/app/submission/direct-submit/direct-submit-sidebar.component.html
- src/app/submission/direct-submit/direct-submit-sidebar.component.ts
- src/app/submission/direct-submit/direct-submit.component.html
- src/app/submission/direct-submit/direct-submit.service.ts
- src/app/submission/edit/subm-edit.component.html
- src/app/submission/edit/subm-edit.component.ts
- src/app/submission/edit/subm-form/feature/subm-feature.component.css
- src/app/submission/edit/subm-sidebar/subm-sidebar.component.html
- src/app/submission/shared/default.template.ts
- src/styles/custom-layout.less
- Simplifies the UI's language and layout.
- Brings validation in line with the rest of the app.
- Refactors the logic handling the convert-submit request sequence.
- Normalises ellipsis usage across the app: only when it requires further interaction in a visual context different from the current one, such as in a modal.
> Improves direct upload UX

- src/app/submission/edit/subm-edit.component.ts
- src/app/submission/edit/subm-form/feature/feature-grid.component.html
- src/app/submission/edit/subm-form/feature/feature-list.component.html
- src/app/submission/edit/subm-sidebar/subm-sidebar.component.html
- src/app/submission/edit/subm-sidebar/subm-sidebar.component.ts
- src/app/submission/shared/pagetab-attributes.utils.ts
- src/app/submission/shared/pagetab.model.ts
- src/app/submission/shared/submission.validator.ts
- src/styles/custom-variables.less
Adds support for optional fields by means of warning cues and probing the required property of the parent type for any field. If optional fields are left empty, these are removed only on submission.
> Warning fields

- src/app/submission/shared/hecatos.template.ts
- src/styles/bootstrap/less/navs.less
- src/styles/old/tree.less
Fixes borders for tabs, makes the order of contact fields be the same across templates and removes commented out styles.
> Tab borders off

- src/app/submission/edit/subm-edit.component.ts
- src/app/submission/edit/subm-form/subm-form.component.html
- src/app/submission/edit/subm-form/subm-form.service.ts
- src/app/submission/edit/submtype-add/submtype-add.component.html
- src/styles/custom-layout.less
Plus some minor fixes and documentation updates.
> Fix for top-level field group validation

- src/app/shared/inline-edit.component.ts
- src/app/submission/edit/subm-edit.component.ts
> Adds missing event parameter to click action handlers

- src/app/submission/direct-submit/direct-submit.component.html
> Fixes the broken link to a study's page on the direct submit view

- src/app/submission/direct-submit/direct-submit.component.html
- src/app/submission/direct-submit/direct-submit.component.ts
- src/app/submission/edit/subm-edit.component.ts
> Redaction changes to Upload View

- src/app/file/file-list/file-list.component.html
- src/app/file/file-list/file-list.component.ts
- src/app/file/file-list/ftp-upload-button/ftp-upload-button.component.html
- src/app/file/file-list/ftp-upload-button/ftp-upload-button.component.ts
- src/app/file/file.module.ts
- src/app/header/app-header/app-header.component.html
- src/app/header/app-header/app-header.component.ts
- src/app/shared/file-upload-button.component.ts
@awaisathar  please have a look. Everything should be strait forward. Let me know if there are any questions. Thx
> first part of pivotal 163289527: moves  secret key button to the file upload page

- src/app/file/file-list/ftp-upload-button/ftp-upload-button.component.css
- src/app/file/file-list/ftp-upload-button/ftp-upload-button.component.html
- src/app/file/file-list/ftp-upload-button/ftp-upload-button.component.ts
- src/app/help/help.component.html
> Add secret key feature to file upload

- src/app/submission/submission-list/subm-list.component.ts
There were two warnings in the console, this PR fixes them.
> Remove an-grid warnings

- src/app/submission/submission-list/subm-list.component.ts
> On resize make columns to fit the available space

- src/app/submission/submission-list/subm-list.component.ts
> Edit submission icon was not visible

- src/app/file/file-list/directory-sidebar/directory-sidebar.component.html
- src/app/file/file-list/file-list.component.html
- src/app/submission/submission-direct/direct-submit-sidebar.component.html
> Cosmetic change to make the toggle button in the direct upload sidebar visible again

- angular.json
- package-lock.json
- package.json
- src/app/app.component.ts
- src/app/submission/submission-edit/subm-edit.component.ts
The issue with `tar` dependency has been fixed and this message can be removed:
> Fix NPM dependency vulnerabilities and some minor issues

- src/app/submission/submission-edit/subm-form/feature/feature-grid.component.css
- src/app/submission/submission-shared/model/templates/eutoxrisk.template.ts
Fixes https://www.pivotaltracker.com/story/show/166116029
> Organisation should be 'select' but it was 'text'

- src/app/submission/submission-edit/subm-edit.component.ts
- src/app/submission/submission-shared/model/pagetab-to-submission.utils.ts
- src/app/submission/submission-shared/model/templates/bia.template.ts
- Fix issue flatting array sections
> Add protocol type to BioImages template

- angular.json
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/file/file-list/ftp-upload-button/ftp-upload-button.component.html
- src/app/file/file-list/ftp-upload-button/ftp-upload-button.component.ts
- src/app/file/file.module.ts
For `MacOS`
For `Windows`
For `Linux`
> Update Aspera docs

- src/app/submission/submission-edit/shared/section-form.ts
- src/app/submission/submission-edit/subm-edit.component.html
- src/app/submission/submission-edit/subm-form/feature/feature-grid.component.html
- src/app/submission/submission-edit/subm-form/feature/feature-list.component.html
- src/app/submission/submission-edit/subm-form/feature/subm-feature.component.html
Remove delete buttons on readonly section
> [Delivers #166436632] Fix readonly mode form

- src/app/submission/submission-edit/shared/subm-edit.service.ts
- src/app/submission/submission-edit/submission-edit.component.ts
- src/app/submission/submission-other/new-submission-button/new-submission-button.directive.ts
- src/app/submission/submission-shared/model/pagetab/pagetab.model.ts
- src/app/submission/submission-shared/submission.service.ts
- src/app/submission/submission-shared/utils/submission-draft.utils.ts
Only edit draft when the form gets dirty
> Change service to use new drafts endpoints

- src/app/submission/submission-list/subm-list.component.ts
- src/app/submission/submission-shared/utils/submission-draft.utils.ts
https://www.pivotaltracker.com/story/show/169313498
- Show all draft submissions in draft list
- Allow to delete draft submissions
> Fix: Show delete button for draft submissions

- src/app/file/file-list/ag-grid/file-type-cell.component.ts
- src/app/file/file-list/file-list.component.ts
> Remove file icon and order files by type

- src/app/submission/submission-edit/submission-edit.component.html
- src/app/submission/submission-edit/submission-edit.component.ts
- Keep track of release date
- Add time zone to the message after creating a submission
> Update model release date if the field changes

- src/app/help/help.component.html
- src/app/submission/submission-edit/submission-edit.component.html
- src/app/submission/submission-results/subm-results-modal.component.html
Help text:
Text in modal after creating a submission:
> Delivers #169500749

- src/app.d.ts
- src/app/extensions/string.extensions.ts
- src/app/submission/submission-shared/model/pagetab-to-submission.utils.ts
- src/app/submission/submission-shared/model/pagetab/pagetab-authors.utils.ts
- src/app/submission/submission-shared/model/templates/submission-type.model.ts
- Allow isReference and reference attribute
- Fix some issues opening EMPIAR studies
> Organisation reference error

- src/app/submission/submission-edit/shared/form-validators.ts
- src/app/utils/index.ts
- src/app/utils/orcid.utils.ts
> Fixes #171307137

- src/app/pages/submission/submission-direct/direct-submit.component.html
- src/app/pages/submission/submission-direct/direct-submit.component.ts
- src/app/pages/submission/submission-list/subm-list.component.ts
- Redirect adding the method param when a direct submission has been created
> Make method param optional

- src/app/pages/submission/submission-edit/shared/form-validators.ts
- src/app/pages/submission/submission-edit/shared/model/feature-form.model.ts
- src/app/pages/submission/submission-edit/shared/subm-edit.service.ts
- src/app/pages/submission/submission-edit/subm-form/input-value/input-value.component.html
- src/app/pages/submission/submission-edit/subm-form/input-value/input-value.component.ts
- src/app/pages/submission/submission-edit/subm-sidebar/subm-check-sidebar/subm-check-sidebar.component.html
- src/app/pages/submission/submission-edit/subm-sidebar/subm-check-sidebar/subm-check-sidebar.component.ts
- src/app/pages/submission/submission-edit/subm-sidebar/subm-edit-sidebar/subm-edit-sidebar.component.html
- src/app/pages/submission/submission-edit/subm-sidebar/subm-edit-sidebar/subm-edit-sidebar.component.ts
- src/app/pages/submission/submission-edit/submission-edit.component.ts
- src/app/pages/submission/submission-shared/model/submission/submission.validator.ts
- src/app/utils/index.ts
- src/app/utils/scroll.utils.ts
- Removes unused code
- Adds utility to have scroll functions
- Scrolls to each element in the submission edit form when items are clicked in the sidebar
> [171928505] Improve error messages and scroll to top

- README.md
- src/app/pages/submission/submission-edit/submission-edit.component.ts
- Update readme
- Always scroll when there are validation errors
> Minor fixes

- src/app/pages/file/file-list/directory-sidebar/directory-sidebar.component.html
- src/app/pages/file/file-list/file-list.component.css
- src/app/pages/file/file-list/file-list.component.html
- src/app/pages/help/help.component.css
- src/app/pages/help/help.component.html
- src/app/pages/submission/submission-direct/direct-submit-sidebar.component.css
- src/app/pages/submission/submission-direct/direct-submit-sidebar.component.html
- src/app/pages/submission/submission-direct/direct-submit.component.css
- src/app/pages/submission/submission-direct/direct-submit.component.html
- src/app/pages/submission/submission-edit/subm-navbar/subm-navbar.component.css
- src/app/pages/submission/submission-edit/subm-navbar/subm-navbar.component.html
- src/app/pages/submission/submission-edit/subm-sidebar/subm-check-sidebar/subm-check-sidebar.component.css
- src/app/pages/submission/submission-edit/subm-sidebar/subm-check-sidebar/subm-check-sidebar.component.html
- src/app/pages/submission/submission-edit/subm-sidebar/subm-check-sidebar/subm-check-sidebar.component.ts
- src/app/pages/submission/submission-edit/subm-sidebar/subm-edit-sidebar/subm-edit-sidebar.component.css
- src/app/pages/submission/submission-edit/subm-sidebar/subm-edit-sidebar/subm-edit-sidebar.component.html
- src/app/pages/submission/submission-edit/subm-sidebar/subm-sidebar.component.html
- src/app/pages/submission/submission-edit/submission-edit.component.css
- src/app/pages/submission/submission-edit/submission-edit.component.html
- src/app/pages/submission/submission-edit/submission-edit.component.ts
- src/app/theme/components/header/header.component.html
- src/app/utils/scroll.utils.ts
- src/style.less
- src/theme/custom-layout.less
- src/theme/custom-navbar.less
- Layout for Submissions was improved
- Layout for Direct Submission was improved
- Layout for Submission Edit was improved
- Layout for File List page was improved
- Layout for Help page was improved
> Extract scrollable section from layout to avoid floats and fixed ements

- src/app/pages/submission/submission-edit/submission-edit.component.html
- src/app/pages/submission/submission-edit/submission-edit.component.ts
See https://www.pivotaltracker.com/n/projects/1189310
> Fix dates mismatch after submitting

- src/app/pages/file/file-list/directory-sidebar/directory-sidebar.component.css
- src/app/pages/file/file-list/directory-sidebar/directory-sidebar.component.html
- src/app/pages/file/file-list/directory-sidebar/directory-sidebar.component.ts
- src/app/pages/file/shared/file.service.ts
> Add a "Group" title in the directories sidebar

- src/app/pages/file/file-list/directory-sidebar/directory-sidebar.component.html
- Hide the group title if sidebar is collapsed
> Add an icon to groups title in directories sidebar

- src/app/pages/file/file-list/directory-path/directory-path.component.css
- src/app/pages/file/file-list/directory-path/directory-path.component.html
- src/app/pages/file/file-list/directory-path/directory-path.component.ts
- src/app/pages/file/file-list/directory-sidebar/directory-sidebar.component.html
- src/app/pages/file/file-list/directory-sidebar/directory-sidebar.component.ts
- src/app/pages/file/file-list/file-list.component.html
- src/app/pages/file/file-list/file-list.component.ts
- src/app/pages/file/shared/path.ts
- Change root path for a home icon
> Makes root path clickable in the files breadcrumb

- src/app/pages/submission/submission-direct/direct-submit-sidebar.component.html
- src/app/pages/submission/submission-direct/direct-submit.component.html
- src/app/shared/file-upload-button.component.ts
- Update direct upload instructions
> Add a Folder Upload button in direct upload page

- src/app/pages/submission/submission-direct/direct-submit-file.component.html
- src/app/pages/submission/submission-direct/direct-submit-file.component.ts
- src/app/pages/submission/submission-direct/direct-submit-sidebar.component.ts
- src/app/pages/submission/submission-direct/direct-submit.component.css
- src/app/pages/submission/submission-direct/direct-submit.component.html
- If there is one single file select it as study
- Use display grid for files grid
- Show warning if no study is selected
> [Delivers 172646480] Direct upload improvements

- src/app/pages/file/file-list/ftp-upload-button/ftp-upload-button.component.html
Sets the link based on the user's OS.
> Update aspera link

- src/app/pages/submission/submission-edit/shared/model/section-form.model.ts
- src/app/pages/submission/submission-edit/shared/subm-edit.service.ts
- src/app/pages/submission/submission-edit/subm-navbar/subm-navbar.component.ts
- src/app/pages/submission/submission-edit/subm-sidebar/subm-edit-sidebar/subm-edit-sidebar.component.ts
- src/app/pages/submission/submission-edit/subm-sidebar/subm-sidebar.component.ts
- src/app/pages/submission/submission-edit/submission-edit.component.html
- src/app/pages/submission/submission-edit/submission-edit.component.ts
https://www.pivotaltracker.com/story/show/174771445
> Fix error switching between subsections

- README.md
- package.json
- src/app/pages/submission/submission-edit/subm-form-input/input-value.component.ts
- src/app/pages/submission/submission-edit/subm-form/feature/feature-grid.component.css
- src/app/pages/submission/submission-edit/subm-form/feature/feature-grid.component.html
- src/app/pages/submission/submission-edit/subm-form/inline-edit/inline-edit.component.html
- src/app/pages/submission/submission-edit/subm-form/inline-edit/inline-edit.component.ts
- src/app/pages/submission/submission-edit/submission-edit.component.html
- Shows an "Optional" label for not required fields
- Changes the script to start the app in dev mode for "dev" (npm run dev)
> Mark optional fields with a label

- src/app/auth/password-reset/password-reset-req.component.html
- src/app/auth/password-reset/password-reset-req.component.ts
> Allow email parameter when setting new password

- src/app/pages/submission/submission-edit/shared/subm-edit.service.ts
- src/app/pages/submission/submission-shared/submission.service.ts
- Backend has changed the endpoint to submit studies. This PR applies the changes to support the new endpoint.
> Change submit endpoint

- src/app/pages/submission/submission-shared/model/templates/proteindesigns.template.ts
Some small changes in protein designs template.
> Change fields for Solution characterization (structure) / Circular Dichroism (CD)

- src/app/app-routing.module.ts
- src/app/auth/password-reset/password-reset.component.html
- src/app/auth/password-reset/password-reset.component.ts
https://www.pivotaltracker.com/story/show/178213145
> [178213145] Change reset page wording when user is setting up password

- src/app/submission/submission-edit/submission-edit.component.html
- src/app/submission/submission-edit/submission-edit.component.ts
- src/app/submission/submission-other/new-submission-button/add-subm-modal.component.html
- src/app/submission/submission-other/new-submission-button/add-subm-modal.component.ts
- src/app/submission/submission-other/new-submission-button/new-submission-button.directive.ts
- src/app/submission/submission-shared/model/templates/bioRaman.template.ts
- src/app/submission/submission-shared/model/templates/default.template.ts
- src/app/submission/submission-shared/model/templates/submission.templates.ts
- src/app/submission/submission-shared/submission-to-pagetab.service.ts
[Delivers #178643150] Use default template for non-template projects
[Delivers #178553866] Show template name on form
> Use default template for non-template projects and show name on form [Delivers #178643150 #178553866]

- src/app/app.config.ts
- src/app/auth/password-reset/password-reset.component.html
- src/app/auth/password-reset/password-reset.component.ts
- src/app/auth/shared/auth.service.ts
- src/config.json
- tasks/build_setup.sh
[Delivers #178213145] Activate ArrayExpress inactive users
> Redirect after password setup

- src/app/app.config.ts
- src/app/app.module.ts
Moves the ReCaptcha key into config.json, and defaults to the key that already exists
> Feature/179120732 Move ReCaptcha key into config.json

- src/app/file/file-select/file-select.component.html
- src/app/file/file-select/file-select.component.ts
- src/app/file/file-select/file-tree.component.html
- src/app/file/file-select/file-tree.component.ts
- src/app/file/upload-file-modal/upload-file-modal.component.html
- src/app/file/upload-file-modal/upload-file-modal.component.ts
- src/app/submission/submission-edit/subm-form-input/input-value.component.html
- src/app/submission/submission-shared/model/templates/bioRaman.template.ts
- src/app/submission/submission-shared/model/templates/submission-type.model.ts
[Fixes #179130287] Allow file-only selection in templates
Update dialouges to reflect if a folder can be selected
> [179130287] Allow file-only selection in templates

- src/app/submission/submission-edit/submission-edit.component.html
- src/app/submission/submission-edit/submission-edit.component.ts
- src/app/submission/submission-shared/model/templates/bia.template.ts
- src/app/submission/submission-shared/model/templates/submission-type.model.ts
- src/images/logo_bia.svg
Add support for creating a banner at the top of a submission form, by adding a `banner` attribute to the template.
Testing: Create/edit a BIA submission, the BioImage Archive logo should appear at the top of the form
> Add support for banner at top of submission form

- src/app/submission/submission-shared/pagetab-to-submission.service.ts
https://www.pivotaltracker.com/story/show/180674197
> Temporary fix for study component not being populated

- src/app/file/file-select/file-select.component.html
- src/app/file/file.module.ts
- src/app/submission/submission-edit/shared/model/table-form.model.ts
- src/app/submission/submission-shared/model/submission/submission.model.ts
- src/app/submission/submission-shared/model/templates/submission-type.model.ts
- src/app/submission/submission-shared/model/templates/submission.templates.ts
- Show tooltip in files inputs, it helps the user to see long file paths
- Fix bug in the new submission modal which is showing the default option twice
> Miscellaneous fixes

- src/app/file/file-list/ftp-upload-button/ftp-upload-button.component.html
https://www.pivotaltracker.com/story/show/181341759
> Add FTP upload tab text changes

- src/app/submission/submission-shared/model/templates/bia-rembi/bia-rembi.template.v1.ts
- src/app/submission/submission-shared/model/templates/submission.templates.ts
https://www.pivotaltracker.com/story/show/181594372
First version (static) of the BIA-REMBI template
Depends on the BIA-REMBI collection existing in the backend
> Add static BIA-REMBI template

- src/app/submission/submission-shared/model/templates/bia/bia.template.v3.ts
https://www.pivotaltracker.com/story/show/181655181
> Update old BIA template FileList explanation link

- src/app/submission/submission-edit/shared/subm-edit.service.ts
- src/app/submission/submission-edit/submission-edit.component.ts
https://www.pivotaltracker.com/story/show/182126211
> Re-add code using collections observable instead of synchronizing with constructor

- src/app/submission/submission-edit/shared/subm-edit.service.ts
- src/app/submission/submission-edit/submission-edit.component.ts
> Re-add code using collections observable instead of synchronizing with constructor (#625)

- README.md
- src/app/submission/submission-edit/shared/subm-edit.service.ts
- src/app/submission/submission-edit/subm-navbar/subm-navbar.component.ts
- src/app/submission/submission-edit/subm-navbar/subm-resubmit-modal.component.html
- src/app/submission/submission-edit/subm-navbar/subm-resubmit-modal.component.ts
- src/app/submission/submission-edit/submission-edit.component.ts
- src/app/submission/submission-edit/submission-edit.module.ts
- src/app/submission/submission-shared/model/templates/bia/bia.template.v2.ts
- src/app/submission/submission-shared/model/templates/bia/bia.template.v3.ts
- src/app/submission/submission-shared/model/templates/bioRaman.template.ts
- src/app/submission/submission-shared/model/templates/default.template.ts
- src/app/submission/submission-shared/model/templates/eutoxrisk.template.ts
- src/app/submission/submission-shared/model/templates/hecatos.template.ts
- src/app/submission/submission-shared/model/templates/proteindesigns.template.ts
- src/app/submission/submission-shared/submission.service.ts
Reverts EBIBioStudies/BioStudyUISub#639
> Revert "Revert "Promoting to beta""

- src/app/submission/submission-list/subm-list.component.ts
https://www.pivotaltracker.com/story/show/182722615
> Fix REQUESTED submission state being removed

- src/app/submission/submission-edit/shared/field-value-validators.ts
- src/app/submission/submission-shared/submission.service.ts
https://www.pivotaltracker.com/story/show/182720666
Pass the accNo to the file list validation endpoint in order to include the files
> Pivotal ID # 182720666: Include ALL File Sources In Files List Validation

- src/app/submission/submission-edit/subm-navbar/subm-resubmit-modal.component.html
https://www.pivotaltracker.com/story/show/180178918
> Fix resubmission modal text

- src/app/submission/submission-edit/field-docs-modal/field-docs-modal.component.html
- src/app/submission/submission-edit/field-docs-modal/field-docs-modal.component.scss
- src/app/submission/submission-edit/field-docs-modal/field-docs-modal.component.ts
- src/app/submission/submission-edit/field-docs-modal/help-contextual/help-contextual.component.html
- src/app/submission/submission-edit/field-docs-modal/help-contextual/help-contextual.component.scss
- src/app/submission/submission-edit/field-docs-modal/help-contextual/help-contextual.component.ts
- src/app/submission/submission-edit/shared/model/column-control.model.ts
- src/app/submission/submission-edit/subm-form/field/subm-field.component.html
- src/app/submission/submission-edit/subm-form/field/subm-field.component.ts
- src/app/submission/submission-edit/subm-form/inline-edit/inline-edit.component.html
- src/app/submission/submission-edit/subm-form/inline-edit/inline-edit.component.ts
- src/app/submission/submission-edit/subm-form/table/table.component.html
- src/app/submission/submission-edit/submission-edit.module.ts
- src/app/submission/submission-shared/model/submission/submission.model.attribute.ts
- src/app/submission/submission-shared/model/submission/submission.model.ts
- src/app/submission/submission-shared/model/templates/bia-rembi/bia-rembi.template.v1.ts
- src/app/submission/submission-shared/model/templates/submission-type.model.ts
https://www.pivotaltracker.com/story/show/182890990
> Add contextual help modal

- src/app/submission/submission-shared/model/templates/bia-rembi/bia-rembi.template.v1.ts
https://www.pivotaltracker.com/n/projects/1189310/stories/183261821
> Add suggested template changes

- src/app/submission/submission-edit/subm-navbar/subm-navbar.component.ts
- src/app/submission/submission-shared/model/organisations.ts
- src/app/submission/submission-shared/model/pagetab/pagetab-authors.utils.spec.ts
- src/app/submission/submission-shared/pagetab-to-submission.service.ts
- src/app/submission/submission-shared/utils/attribute.utils.ts
- src/app/submission/submission-shared/utils/link.utils.ts
- src/app/submission/submission-shared/utils/section.utils.ts
- Suppress empty `valqual` and `reference` attributes
- Remove deleted orgs
- Suppress file update confirmation for AE
> [Delivers #183501957 #183000323 #183501957]

- src/app/submission/submission-edit/submission-edit.component.ts
- src/app/submission/submission-shared/model/submission/submission.validator.ts
https://www.pivotaltracker.com/story/show/183626624
> Add recursive error checks for toplevel isValid

- src/app/submission/submission-shared/model/templates/bia-rembi/bia-rembi.template.v1.ts
- src/app/submission/submission-shared/model/templates/submission-type.model.ts
https://www.pivotaltracker.com/story/show/183628684
> Add support for optional subsections

- src/app/submission/submission-edit/field-docs-modal/field-docs-modal.component.html
- src/app/submission/submission-edit/field-docs-modal/field-docs-modal.component.ts
- src/app/submission/submission-shared/model/templates/bia-rembi/bia-rembi.template.v1.ts
https://www.pivotaltracker.com/story/show/183747153
> Add support for html in contextual help

- src/app/submission/submission-shared/submission.service.ts
https://www.pivotaltracker.com/story/show/183389588
Only SUBMISSION files source should be used for metadata updates
> Pivotal ID # 183389588: Files Source For Metadata Updates

- src/app/submission/submission-shared/model/templates/bia/bia.template.v4.ts
https://www.pivotaltracker.com/story/show/183889547
> Rix REMBI associations table

- src/app/submission/submission-shared/submission.service.ts
https://www.pivotaltracker.com/story/show/183523291
Format the AttachTo attribute with the format expected by the backend
> Pivotal ID # 183523291: Collection Selection Ignored When Submitting Pagetab Via ST

- src/app/submission/submission-edit/submission-edit.component.html
- src/app/submission/submission-shared/model/submission/submission.model.table.spec.ts
- src/app/submission/submission-shared/model/templates/arrayexpress.template.ts
- src/app/submission/submission-shared/model/templates/bia/bia.template.v0.ts
- src/app/submission/submission-shared/model/templates/bia/bia.template.v4.ts
- src/app/submission/submission-shared/model/templates/bia/index.ts
- src/app/submission/submission-shared/model/templates/submission-type.model.ts
- src/app/submission/submission-shared/model/templates/submission.templates.ts
https://www.pivotaltracker.com/story/show/184258898
> Add support for inheritable displayAnnotations in SectionType

- src/app/submission/submission-edit/subm-form/table/subm-table.component.ts
- src/app/submission/submission-edit/subm-sidebar/subm-sidebar.component.ts
https://www.pivotaltracker.com/story/show/184519501
> Fix leftover reference to deleted sections

- server/app.ts
- server/rabbitmq/rabbitmq-consumer.ts
- server/submission-status/submission-status-processor.ts
- src/app/submission/submission-shared/model/templates/default.template.ts
https://www.pivotaltracker.com/story/show/182952538
> Add reconnection logic if rabbit server dies

- src/app/submission/submission-shared/model/submission/submission.model.ts
https://www.pivotaltracker.com/story/show/184757845
> Fix section tables not added when new sections are added

- src/app/file/file-list/file-list.component.ts
> [Delivers #186588838] Suppress overwrite message if folders don't exist
